Build mac universal binary

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -10,9 +10,47 @@ jobs:
     build:
         uses: ./.github/workflows/build.yml
 
+    merge_macos:
+        runs-on: macos-15
+        needs: build
+        steps:
+            - name: Checkout code
+              uses: actions/checkout@v4
+
+            - name: Download all artifacts
+              uses: actions/download-artifact@v4
+              with:
+                  path: dist
+
+            - name: Merge macOS universal bundle
+              run: |
+                  set -e
+                  mkdir dist/output
+
+                  if [[ ! -f dist/mac-arm64/mac-arm64.zip || ! -f dist/mac-x86_64/mac-x86_64.zip ]]; then
+                      echo "Missing mac-arm64.zip or mac-x86_64.zip"
+                      exit 1
+                  fi
+                  unzip -q dist/mac-arm64/mac-arm64.zip -d dist/mac-arm64
+                  unzip -q dist/mac-x86_64/mac-x86_64.zip -d dist/mac-x86_64
+                  # extract API version from the bundle folder name
+                  api_ver=$(basename dist/mac-arm64/plugins-api* | sed 's/plugins-api//')
+
+                  ./scripts/merge_universal.sh \
+                      dist/mac-arm64/plugins-api${api_ver}/XDAQ-OE.bundle \
+                      dist/mac-x86_64/plugins-api${api_ver}/XDAQ-OE.bundle \
+                      dist/mac-universal/plugins-api${api_ver}/XDAQ-OE.bundle
+                  7za a dist/mac-universal.zip ./dist/mac-universal/*
+
+            - name: Upload merged macOS bundle
+              uses: actions/upload-artifact@v4
+              with:
+                  name: mac-universal
+                  path: dist/mac-universal.zip
+
     publish:
         runs-on: ubuntu-24.04
-        needs: build
+        needs: [merge_macos]
 
         steps:
             - name: Download all artifacts
@@ -34,42 +72,47 @@ jobs:
                   ref="${{ github.ref_name }}"
                   if [[ "$ref" != xdaq-v* ]]; then
                       echo "Not a release tag: $ref"
-                      exit 1
+                      ref="xdaq-v0.0.0"  # Default to a dummy version if not a valid tag
                   fi
 
                   upload_tag="${ref#xdaq-v}"
                   api_ver="10"
 
-                  for f in dist/*.zip; do
-                      base=$(basename "$f" .zip)
-                      if [[ "$base" == windows-x86_64 ]]; then
-                          new_name="XDAQ-windows_${upload_tag}-API${api_ver}.zip"
-                      elif [[ "$base" == mac-arm64 ]]; then
-                          new_name="XDAQ-mac_${upload_tag}-API${api_ver}.zip"
-                      elif [[ "$base" == linux-x86_64 ]]; then
-                          new_name="XDAQ-linux_${upload_tag}-API${api_ver}.zip"
-                      else
-                          echo "Unknown platform in $base, skipping"
+                  if [[ -z dist/windows-x86_64 ]]; then
+                        echo "Missing dist/windows-x86_64"
+                        exit 1
+                  fi
+                  win_new_name="XDAQ-windows_${upload_tag}-API${api_ver}.zip"
+                  mv dist/windows-x86_64.zip dist/$win_new_name
+                  echo "Created: dist/$win_new_name"
+
+                  if [[ -z dist/mac-universal ]]; then
+                        echo "Missing dist/mac-universal"
+                        exit 1
+                  fi
+                  mac_new_name="XDAQ-mac_${upload_tag}-API${api_ver}.zip"
+                  mv dist/mac-universal.zip dist/$mac_new_name
+                  echo "Created: dist/$mac_new_name"
+
+                  if [[ -z dist/linux-x86_64 ]]; then
+                          echo "Missing dist/linux-x86_64"
                           exit 1
-                      fi
-                      mv "$f" "dist/$new_name"
+                  fi
+                  linux_new_name="XDAQ-linux_${upload_tag}-API${api_ver}.zip"
+                  mv dist/linux-x86_64.zip dist/$linux_new_name
+                  echo "Created: dist/$linux_new_name"
 
-                      echo "Created: dist/$new_name"
+                  if [[ -z "${{ secrets.artifactoryApiKey }}" ]]; then
+                      echo "No Artifactory API key set, skipping upload"
+                      exit 0
+                  fi
 
-                      # Upload
-                      if [[ "$base" == windows-x86_64 ]]; then
-                        curl -H "X-JFrog-Art-Api:${{ secrets.artifactoryApiKey }}" -T "dist/$new_name" \
-                          "https://openephys.jfrog.io/artifactory/XDAQ-plugin/windows/$new_name"
-                      elif [[ "$base" == mac-arm64 ]]; then
-                        curl -H "X-JFrog-Art-Api:${{ secrets.artifactoryApiKey }}" -T "dist/$new_name" \
-                          "https://openephys.jfrog.io/artifactory/XDAQ-plugin/mac/$new_name"
-                      elif [[ "$base" == linux-x86_64 ]]; then
-                        curl -H "X-JFrog-Art-Api:${{ secrets.artifactoryApiKey }}" -T "dist/$new_name" \
-                          "https://openephys.jfrog.io/artifactory/XDAQ-plugin/linux/$new_name"
-                      else
-                        echo "No Artifactory API key set, skipping upload"
-                      fi
-                  done
+                  curl -H "X-JFrog-Art-Api:${{ secrets.artifactoryApiKey }}" -T "dist/$win_new_name" \
+                    "https://openephys.jfrog.io/artifactory/XDAQ-plugin/windows/$win_new_name"
+                  curl -H "X-JFrog-Art-Api:${{ secrets.artifactoryApiKey }}" -T "dist/$mac_new_name" \
+                    "https://openephys.jfrog.io/artifactory/XDAQ-plugin/mac/$mac_new_name"
+                  curl -H "X-JFrog-Art-Api:${{ secrets.artifactoryApiKey }}" -T "dist/$linux_new_name" \
+                    "https://openephys.jfrog.io/artifactory/XDAQ-plugin/linux/$linux_new_name"
 
             - name: Upload dist folder
               uses: actions/upload-artifact@v4
